config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new]
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  has_secure_password
  before_save { self.email = email.downcase }
  validates :username, presence: true,
  uniqueness: { case_sensitive: false },
  length: { minimum: 3, maximum: 25}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
  uniqueness: { case_sensitive: false },
  format: {with: VALID_EMAIL_REGEX}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  def logged_in?
    !!current_user
  end
  def require_user
    if !logged_in?
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update]
  def new
    @article = Article.new
  end
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      redirect_to article_path(@article)
    else
      render 'new'
    end
    
  end

  def show
    
  end

  def edit
    
  end

  def update
    
    if @article.update(article_params)
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def index
    @articles = Article.all
  end

  def destroy
    
    @article.destroy
    redirect_to articles_path
  end
  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :image)
    end

    def require_same_user
      if current_user != @article.user
        redirect_to root_path
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      render 'new'
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  def edit
    
  end
  def update
    
    if @user.update(user_params)
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    
  end
  private 
  def user_params
    params.require(:user).permit(:username,:email, :password, :image)
  end
  def set_user
    @user = User.find(params[:id])
  end
  def require_same_user
    if current_user != @user
      redirect_to root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>

<div class="container2">
  <div class="jumbotron2">
    <div class="row2">
    <div class="col-lg-4 col-sm-6">
      <div class="thumbnail2">
      <ul class="ul">
        <li><%= link_to article.title, article_path(article), class: "titlearticles" %></li>
         <li>
          <% if article.image %>
            <img class="imgarticles" src="<%= article.image %>">
          <% end %>
        </li>
        <li id="titlearticle"><small>Created by:</small>

         <%= article.user.username if article.user%>
         <% if article.user.image %>
         <img width="50" height="50" style="border-radius: 50%; object-fit: cover;" src="<%= article.user.image if article.user %>">
         <% end %>
        </li>
      </ul>
        
      </div>
    </div>
  </div>
  </div>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= form_for @article do |a| %>
  <p>
    <%= a.label :title %>
    <%= a.text_field :title %>
  </p>
  <p>
    <%= a.label :image %>
    <%= a.text_field :image %>
  </p>
  <p>
    <%= a.submit %>  
  </p>

<% end %>

<p>
  <%= link_to 'Back', articles_path %>
</p>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
<% if @article.errors.any? %>
  <h2>Error</h2>
<% end %>

<%= render 'form' %>
  

app/views/articles/index.html.erb
<%= render 'welcome/header' %>
<div class="main2" style="margin-top: 0;">
  <div class="container3">
    <h1 id="articlesheader">OUR PRODUCTS</h1>
  </div>
</div>
<% if logged_in? && current_user %>
<p style="padding-top: 10px; padding-left: 10px;">
  <%= link_to 'Create new', new_article_path, class: "btn btn-lg btn-success" %>
</p>
<% end %>

<%= render 'article', obj: @articles %>

app/views/articles/new.html.erb
<%= render 'welcome/header' %>
<div class="formcontrol0">
<center>
  <h1>New Product</h1>
<%= form_for @article, class: "form-horizontal" do |a|  %>
  <p>
    <%= a.label :title, class: "form-control2" %>
    <%= a.text_field :title, class: "form-control", placeholder: "Enter a title" %>
  </p>
  <p>
    <%= a.label :image, class: "form-control2" %>
    <%= a.text_field :image, class: "form-control", placeholder: "Enter an image" %>
  </p>
  <div class="button2">
    <p>
    <%= a.submit %>
    </p>
    <% end %>
  </div>
  
</center>

</div>

app/views/articles/show.html.erb
<%= render 'welcome/header' %>
<ul class="2s" style="text-align: center">
  <li class="2s"><h2 align="center"><%= @article.title %></h2></li>
  <li><img src="<%= @article.image %>" width="650" height="450"  id="imgarticle"></li>
</ul>


<div class="well col-xs-8 col-xs-offset-2">

<% if @article.user %>

<ul class="listing">

<div class="row center">

<div class="col-md-4 col-md-offset-4">

<li>Created by:</li>

<li><img id="sellerimg" width="150" height="150" src="<%= @article.user.image %>"></li>

<li class="article-title">

<%= link_to @article.user.username, user_path(@article.user) %>

</li>



<li><small>

<%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>

</small></li>

</div>

</div>

</ul>

<% end %>



<div class="article-actions">

<% if logged_in? && current_user == @article.user %>

<%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>

<%= link_to "Delete this article", article_path(@article), method: :delete,

data: { confirm: "Are you sure you want to delete the article?"},

class: "btn btn-xs btn-danger" %>

<% end %>

<%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>

</div>

</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">

<div class="container-fluid">

<!-- Brand and toggle get grouped for better mobile display -->

<div class="navbar-header">

<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

<span class="sr-only">Toggle navigation</span>

<span class="icon-bar"></span>

<span class="icon-bar"></span>

<span class="icon-bar"></span>

</button>

<%= link_to "Alpha blog", root_path, class: "navbar-brand", id: "logo" %>

</div>

<!-- Collect the nav links, forms, and other content for toggling -->

<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

<ul class="nav navbar-nav">

<li><%= link_to "Articles", articles_path %></li>

<li><%= link_to "Users", users_path %></li>

<% if logged_in? %>

<li class="dropdown">

<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>

<ul class="dropdown-menu">

<li><%= link_to "New Article", new_article_path %></li>

<li><a href="#">Another action</a></li>

<li><a href="#">Something else here</a></li>

<li role="separator" class="divider"></li>

<li><a href="#">Separated link</a></li>

<li role="separator" class="divider"></li>

<li><a href="#">One more separated link</a></li>

</ul>

</li>

<% end %>

</ul>

<form class="navbar-form navbar-left" role="search">

<div class="form-group">

<input type="text" class="form-control" placeholder="Search">

</div>

<button type="submit" class="btn btn-default">Submit</button>

</form>

<ul class="nav navbar-nav navbar-right">

<% if logged_in? %>

<li><%= link_to 'Log out', logout_path, method: :delete %></li>

<li class="dropdown">

<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile<span class="caret"></span></a>

<ul class="dropdown-menu">

<li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>

<li><%= link_to "View your profile", user_path(current_user) %></li>

<li><a href="#">Something else here</a></li>

<li role="separator" class="divider"></li>

<li><a href="#">Separated link</a></li>

</ul>

</li>

<% else %>

<li><%= link_to 'Log in', login_path %></li>

<li><%= link_to 'Sign up', signup_path %></li>

<% end %>

</ul>

</div><!-- /.navbar-collapse -->

</div><!-- /.container-fluid -->

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musicians</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:700" rel="stylesheet">
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="formcontrol0">
    <p>
<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |a| %>
</p>
<p>
  <%= a.label :username, class: "form-control2" %>
</p>

<p>
  <center><%= a.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %></center> 
</p>
<p>
  <%= a.label :email, class: "form-control2" %>
</p>
<p>
  <center><%= a.email_field :email, class: "form-control", placeholder: "Enter email"%></center> 
</p>

<p>
  <%= a.label :password, class: "form-control2" %>
</p>
<p>
  <center> <%= a.password_field :password, class: "form-control", placeholder: "Enter username" 
  %></center>
</p>
<p>
  <%= a.label :image, class: "form-control2" %>
</p>
<p>
  <center><%= a.text_field :image, class: "form-control", placeholder: "Enter image" %></center>   
</p>
<div class="button2">
  <p><%= a.submit(@user.new_record? ? "Sign up" : "Update", class: "two") %></p>
  <% end %> 
</div>
</div>

 


<div class="buttons">
  <p id="two" style="margin-left: 15px">
  <%= link_to "Back", articles_path, class: "two" %>
  </p>
</div>
  
  

 

app/views/users/edit.html.erb
<div class="main">
  <div class="container">
    <h1 id="first">Edit account</h1>
    <%= render 'form' %>
  </div>  
</div>

app/views/users/index.html.erb
<%= render 'welcome/header' %>
<div class="main4">
  <div class="container4">
    <h1 class="sellerbanner">All sellers</h1>
  </div>
</div>

<% @users.each do |user| %>
<ul class="usersAll">
  
</ul>

<div class="container2">
  <div class="jumbotron2">
    <div class="row2">
    <div class="col-lg-4 col-sm-6">
      <div class="thumbnail2">
      <ul class="ul">
        <% if user.image%>
    <li><img class="imguser" width="150" height="150" src="<%= user.image %>"></li>
  <% end %>
  <li><%= link_to user.username, user_path(user) %></li>
  <li><%= pluralize(user.articles.count, "article") if user.articles %>
    
  </li>
      </ul>
        
      </div>
    </div>
  </div>
  </div>
</div>
<% end %>

app/views/users/new.html.erb
<%= render 'welcome/header' %>
<div class="main5">
  <div class="container5">
    <h1 id="firsth1">New account</h1>
    <%= render 'form' %>
  </div>  
</div>

app/views/users/show.html.erb
<%= render 'welcome/header' %>
<div id="show2">
  <h1><%= @user.username %>'s page</h1>
  <% if @user.image %>
    <img id="userimg" src="<%= @user.image %>">
  <% else %>
    <img src="https://imageog.flaticon.com/icons/png/512/36/36601.png?size=1200x630f&pad=10,10,10,10&ext=png&bg=FFFFFFFF">
  <% end %>
  <h3>Products:</h3>
  <%= render 'articles/article', obj: @user.articles %>
</div>

app/views/welcome/_header.html.erb
<nav class="navbar navbar-default" style="background-color: white; margin-bottom: 0;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" style="border: none">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Food</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" >
      <ul class="nav navbar-nav" >
        <li><%= link_to 'Sellers', users_path %></li>
        <li><%= link_to 'Products', articles_path %></li>
       
      </ul>
      <form class="navbar-form navbar-left">
        
        
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Log In', login_path %></li>
       
        <%= link_to 'Sign Up', signup_path, class: "btn bnt-lg btn-warning", style: "margin-top: 10px; margin-left: 10px;" %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/welcome/index.html.erb
<%= render 'header' %>

<div class="main">
  <div class="container">
    <p>Food is better when you start from scratch</p> 
    <%= link_to 'Sign Up', signup_path, class: "btn bnt-lg btn-success" %>
  </div>
</div>